name: CI

on:
  push:
  pull_request:

jobs:

  # Enforces the consistency of code formatting using `.editorconfig` and the `dotnet-format` tool.
  check-format:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Restore tools
        run: dotnet tool restore
      - name: Check format
        run: dotnet format --check --exclude submodules
  
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    strategy:
      matrix:
        os: [windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        if: runner.os != 'Windows'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Build_Debug_Skip_Unit_Test
        run: .\build.ps1 -SkipUnitTest -Configuration Debug
      - name: Build_Release
        run: .\build.ps1 -Configuration Release
